name: Deploy API to Firebase on merge
"on":
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "14.x"
      - name: Installing Function Dependencies
        run: npm install
        working-directory: api/functions
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        working-directory: api
      - name: Deploying to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        working-directory: api
