name: Build on PR
"on": pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Installing Client Dependencies
        run: yarn install
        working-directory: client
      - name: Building
        run: yarn run build
        working-directory: client
